version: '2'
services:
    xen-orchestra:
        image: yobasystems/alpine-xen-orchestra:aarch64
        command: ./bin/xo-server
        container_name: xoa
        ports:
            - "8000:8080"
        depends_on:
            - redis
        environment:
            - NODE_ENV=production
        volumes:
            - /data/xoa/server:/app/data
    redis:
        container_name: xoa-redis
        image: yobasystems/alpine-redis:aarch64
        command: redis-server --appendonly yes
        volumes:
            - /data/xoa/redis:/data
